instances:
  # The prometheus endpoint to query from
  - openmetrics_endpoint: https://cp-kafka-connect-test-new-2-dc-evst-nonprod.apps.dn01.exxonmobil.com/metrics
    namespace: "myapp"
    metrics: [{"^kafka_connect_.+": {"type": "gauge"}}, ".+"]
